sequenceDiagram
    autonumber
    actor Device
    participant UIM as MAUI_UI
    participant Narr as NarrationEngine
    participant SyncM as SyncService_Maui
    participant AnaC as AnalyticsController
    participant AnaS as AnalyticsService
    participant DB as AppDbContext_SQL
    UIM->>Narr: TriggerPlayback
    Narr->>Narr: InsertLocalLog
    SyncM->>AnaC: BatchLog
    AnaC->>AnaS: SaveLogsAsync
    AnaS->>DB: InsertPlaybackLogs
    AnaC-->>SyncM: logs_saved

