sequenceDiagram
    autonumber
    actor Admin
    participant UIA as Admin_UI
    participant AnaC as AnalyticsController
    participant AnaS as AnalyticsService
    participant DB as AppDbContext_SQL
    UIA->>AnaC: Summary_TopPois_TopDevices_History_ActiveUsers
    AnaC->>AnaS: GetSummaryAsync_GetTopPoisAsync_GetTopDevicesAsync_GetUsageHistoryAsync_GetActiveUsersAsync
    AnaS->>DB: QueryAnalytics
    AnaC-->>UIA: analytics_data
