sequenceDiagram
    autonumber
    actor Admin
    participant UIA as Admin_UI
    participant TourC as TourController
    participant TourS as TourService
    participant DB as AppDbContext_SQL
    UIA->>TourC: Create
    TourC->>TourS: CreateAsync
    TourS->>DB: SaveTourStops
    TourC-->>UIA: tour_detail
