sequenceDiagram
    autonumber
    actor Vendor
    participant UIV as Vendor_UI
    participant VC as VendorController
    participant UM as UserManager
    UIV->>VC: ChangePassword
    VC->>UM: ChangePasswordAsync
    VC-->>UIV: password_result
